project:
  type: website

website:
  title: "Margarita Valdés A., PhD"
  description: "This is Margarita Valdes' personal Data Analysis portfolio"
  site-url: "https://margar1tava.quarto.pub/portfolio/"
  navbar:
    right: 
      - text: Portfolio
        href: blog.qmd
      - text: Resume
        href: resume.qmd
      - icon: github
        href: https://github.com/MARgar1taVA
      - icon: linkedin
        href: https://www.linkedin.com/in/m-valdes-aleman/
      - icon: envelope-fill
        href: mailto:valdes.aleman.margarita@gmail.com 
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: tango

editor: visual

